server:
  port: 2222


spring:
  application:
    name: MicroService-Eureka-Provider

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zexee3xsm35urxe6vo.mysql.rds.aliyuncs.com:3306/zrszt
    username: root
    password: aep7Eiphoh2Gaophugh6eel#o
    hikari:
      minimum-idle: 5
      idle-timeout: 0
      maximum-pool-size: 10
      auto-commit: true
      pool-name: YoungHikariConnectionPool
      max-lifetime: 0
      connection-timeout: 0
      connection-test-query: SELECT 1


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.young.zrszt.entity
  configuration:
    map-underscore-to-camel-case: true
