server:
  port: 2222


spring:
  application:
    name: MicroService-Eureka-Provider

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.198.37.239:3306/zrszt
    username: root
    password: xijuzhihui
    hikari:
      minimum-idle: 5
      idle-timeout: 0
      maximum-pool-size: 10
      auto-commit: true
      pool-name: YoungHikariConnectionPool
      max-lifetime: 0
      connection-timeout: 0
      connection-test-query: SELECT 1


  elasticsearch:
    username: elastic
    password: 180420
    cert: http.p12
    host: 139.198.37.239
    port: 9200

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.young.zrszt.entity
  configuration:
    map-underscore-to-camel-case: true


zrszt:
  upload:
    host: http://139.198.37.239/zrfiles
    path: /usr/local/zrszt
    image:
      url: ${zrszt.upload.path}/avatar/